#ifndef MEMSIM_ARG_H
#define MEMSIM_ARG_H

#include <stdbool.h>

/**
 * Page Replacement Algorithm
 */
typedef enum ALGO
{
  FIFO,
  LRU,
  CLOCK,
  ECLOCK
} ALGO;

#define INVALID_ALGO -1

/**
 * Simulator Command-line args
 * @level: number of levels in page table. 1 or 2
 * @addrfile: name/path of file containing memory references
 * @swapfile: name/path of binary file storing pages
 * @fcount: number of frames to be used by the simulated program
 * @algo: page replacement algorithm option
 * @tick: timer tick period
 * @outfile: name/path of the output file generated by simulator
 */
typedef struct cmd_args
{
  int level;
  char *addrfile;
  char *swapfile;
  int fcount;
  ALGO algo;
  int tick;
  char *outfile;
} cmd_args;

cmd_args *new_cmdargs(void);

void free_cmdargs(cmd_args *);

void print_cmdargs(const cmd_args *);

bool init_cmdargs(cmd_args *, const int argc, const char *argv[]);

#endif